### ISSUE TITLE
Incorporate changes of Kirby 2.2

### ISSUE THREAD

**Issue by dweidner** [dweidner/kirby-comments#2]
Now that Kirby 2.2 is live with the essential bug fixes for the Toolkit integrated, the plugin installation should be working without additional core hacks. 
- [x] Test installation routine
- [x] Ensure plugin is compatible with 2.2
- [ ] Setup a test site
- [ ] Update installation guide

**Comment by buditanrim** [comment]
how is this doing? Is it good to use with newest Kirby version (2.2) ?

**Comment by dweidner** [comment]
My last Test with version 2.2-dev worked. There are some features which might be handy to integrate into this plugin. Especially the improvements of the panel.

Planing to setup a test site and more documentation.

**Comment by dweidner** [comment]
Going to optimize this plugin for use with Kirby 2.3 as it provides a lot of additions which previously could only be achieved with ‘hacks’
