### ISSUE TITLE
Can delete/edit comments on localhost but not on server

### ISSUE THREAD

**Issue by DerZyklop** [dweidner/kirby-comments#5]
I had my website running on my computer on localhost, when i was working through the kirby-comments wizard. Everything worked fine. 

I uploaded my project to my server and since then i have the issue:

**When i log into my panel as admin, i still can not delete or edit comments.** Plus the contact-form doesn't change/does not recognize me after i loggen in to the panel.

All files are identical on server and local.

Do you have an idea whats happening here?

PS: great plugin! thanks!

**Comment by dweidner** [comment]
In the latest Kirby version a lot has changed in the panel. I will update the Comments Field as soon as possible to incorporate these changes. Can you tell me the PHP version you are using on your localhost/server?
